apiVersion: apps/v1
kind: Deployment
metadata:
  name: jen12-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jen12
  template:
    metadata:
      labels:
        app: jen12
    spec:
      containers:
        - name: jen12
          image: uya12345/jen12
          ports:
            - containerPort: 80
          