apiVersion: apps/v1
kind: Deployment
metadata:
  name: jen12-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jen12
  template:
    metadata:
      labels:
        app: jen12
    spec:
      containers:
        - name: jen12
          image: uya12345/jen12
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Served by $(hostname)" >> /usr/local/apache2/htdocs/index.html && \
              httpd-foreground
 